### ISSUE TITLE
Iterating over features?

### ISSUE THREAD

**Issue by yahelc** [userapp-io/userapp-python#1]
Hi all,

I'm trying to figure out how to make the `user.features` object iterable. I'm trying to iterate over the features to figure out which is enabled, and I can't seem to make that object iteratable. 

How can I iterate over a user's features object? I can't seem to get around the strictures of what `to_object` is doing. 

Thanks

**Comment by rorheden** [comment]
Thanks for reporting it. Can't see how I could have missed that!

I have commited a fix and pushed a new PyPI release (0.2.6). So the object returned should now be iterable.

Let me know how it works.

**Comment by rorheden** [comment]
Something worth noting is that the object returned also now implements __contains__, which means that you can use _in_, i.e.

```
if 'express_delivery' in user.features:
    print("user has express delivery")
```

**Comment by yahelc** [comment]
Thanks! Appreciate the quick fix. I was sure I was going crazy.

**Comment by rorheden** [comment]
No problem :+1: If you'd like sharing your experience with UserApp and how it's been integration-wise with Python, I would love to hear that. Anything that can help us bettering! :-) Feel free to email me at robin.orheden[ at ]userapp[ dot ]io anytime.
